### ISSUE TITLE
Custom formula

### ISSUE THREAD

**Issue by berkinet** [perlman/phidgets-indigo#3]
Allow the ability to define a custom formula to be applied to an analog device's sensorOutput. Also allow a custom state name to be defined for the formula, and the ability to use that state as the display state.

**Comment by berkinet** [comment]
Added UI support for custom formula (lambda) and custom state name for voltageRatio devices to Devices.xml.  
The UI display for a custom formula is keyed to selecting the generic VR device.
Then, added code to voltageratioinput.py to look for the custom info if the device type is 0 (generic), and apply the formula.

Still need to create the new custom state so it can be updated.

(this is in the NEW-VINT-Devices branch)

**Comment by berkinet** [comment]
Code added to add the custom display state name to the indigo device and also set it as the device displayState.  Should use of the custom state name be optional?

**Comment by berkinet** [comment]
Question... is a custom formula of value for voltage devices?

**Comment by berkinet** [comment]
Done for both voltage and voltageRation devices.

**Comment by perlman** [comment]
Added to master with https://github.com/perlman/phidgets-indigo/commit/241c1828f81642e9529301b55a715fb51e22e61d.
